name: FE-app
on:
  pull_request:
    branches:
      - main
      - main-v2
    paths:
      # relevant
      - "client-side-js/**"
      - "examples/**"
      - "scripts/**"
      - "src/**"
      # don't run on changes to these
      - "!.husky/**"
      - "!.vscode/**"
      - "!docs/**"
      - "!.*"
      - "!*.md"
      - "!*.cjs"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      ### no mas since wdio^8 allows for auto-download of matching chromedriver for the env
      ### -> we save CI time!
      ### yet leaving this as ref
      # - name: update chrome
      #   run: |
      #     wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      #     sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      #     sudo apt-get update
      #     sudo apt-get --only-upgrade install google-chrome-stable
      #     # check chrome version
      #     google-chrome --version

      - name: check out repo
        uses: actions/checkout@v3

      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      # install both module + sample app(s) deps
      - name: install packages (wdi5 + sample app(s))
        run: |
          npm pkg delete scripts.prepare
          npm ci

      # build things
      - name: build
        run: npm run build

      # run fiori elements-related wdi5 tests
      # explicit headless mode!
      - name: test fe-app
        run: npm run test:fe-app
